package com.dpe.common.editor;

import com.dpe.common.model.Advancement;
import com.dpe.common.model.Datapack;
import com.dpe.common.model.LootTable;
import com.dpe.common.model.McFunction;
import com.dpe.common.model.ResourceLocation;
import com.dpe.common.model.Tag;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonObject;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

/**
 * 数据包导出器，生成符合 vanilla 目录结构的 zip 或目录。
 * pack.mcmeta 的 pack_format=48（对应 1.21.1）。
 */
public final class DatapackExporter {

    public static final int PACK_FORMAT = 48;
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

    private DatapackExporter() {
    }

    /** 导出到 zip 流。 */
    public static void exportToZip(Datapack dp, OutputStream out) throws IOException {
        try (ZipOutputStream zos = new ZipOutputStream(out, StandardCharsets.UTF_8)) {
            writePackMcmetaZip(zos, dp.namespace());
            writeFunctionsZip(zos, dp);
            writeTagsZip(zos, dp);
            writeAdvancementsZip(zos, dp);
            writeLootTablesZip(zos, dp);
        }
    }

    /** 导出到目录。 */
    public static void exportToDir(Datapack dp, Path dir) throws IOException {
        Files.createDirectories(dir);
        writePackMcmetaDir(dir, dp.namespace());
        writeFunctionsDir(dir, dp);
        writeTagsDir(dir, dp);
        writeAdvancementsDir(dir, dp);
        writeLootTablesDir(dir, dp);
    }

    // ---------- zip 写入 ----------
    private static void writePackMcmetaZip(ZipOutputStream zos, String ns) throws IOException {
        JsonObject pack = new JsonObject();
        pack.addProperty("pack_format", PACK_FORMAT);
        pack.addProperty("description", "Datapack " + ns + " (generated by dpe editor)");
        JsonObject root = new JsonObject();
        root.add("pack", pack);
        zos.putNextEntry(new ZipEntry("pack.mcmeta"));
        zos.write(GSON.toJson(root).getBytes(StandardCharsets.UTF_8));
        zos.closeEntry();
    }

    private static void writeFunctionsZip(ZipOutputStream zos, Datapack dp) throws IOException {
        for (McFunction fn : dp.functions()) {
            String entry = "data/" + fn.id().namespace() + "/functions/" + fn.id().path() + ".mcfunction";
            zos.putNextEntry(new ZipEntry(entry));
            zos.write(fn.toFileContent().getBytes(StandardCharsets.UTF_8));
            zos.closeEntry();
        }
    }

    private static void writeTagsZip(ZipOutputStream zos, Datapack dp) throws IOException {
        for (Tag tag : dp.tags()) {
            String entry = "data/" + tag.id().namespace() + "/tags/" + tag.type() + "/" + tag.id().path() + ".json";
            zos.putNextEntry(new ZipEntry(entry));
            zos.write(tagToJson(tag).getBytes(StandardCharsets.UTF_8));
            zos.closeEntry();
        }
    }

    private static void writeAdvancementsZip(ZipOutputStream zos, Datapack dp) throws IOException {
        for (Advancement adv : dp.advancements()) {
            String entry = "data/" + adv.id().namespace() + "/advancements/" + adv.id().path() + ".json";
            zos.putNextEntry(new ZipEntry(entry));
            zos.write(GSON.toJson(adv.raw()).getBytes(StandardCharsets.UTF_8));
            zos.closeEntry();
        }
    }

    private static void writeLootTablesZip(ZipOutputStream zos, Datapack dp) throws IOException {
        for (LootTable lt : dp.lootTables()) {
            String entry = "data/" + lt.id().namespace() + "/loot_tables/" + lt.id().path() + ".json";
            zos.putNextEntry(new ZipEntry(entry));
            zos.write(GSON.toJson(lt.raw()).getBytes(StandardCharsets.UTF_8));
            zos.closeEntry();
        }
    }

    // ---------- 目录写入 ----------
    private static void writePackMcmetaDir(Path dir, String ns) throws IOException {
        JsonObject pack = new JsonObject();
        pack.addProperty("pack_format", PACK_FORMAT);
        pack.addProperty("description", "Datapack " + ns + " (generated by dpe editor)");
        JsonObject root = new JsonObject();
        root.add("pack", pack);
        Files.writeString(dir.resolve("pack.mcmeta"), GSON.toJson(root), StandardCharsets.UTF_8);
    }

    private static void writeFunctionsDir(Path dir, Datapack dp) throws IOException {
        for (McFunction fn : dp.functions()) {
            Path p = dir.resolve("data/" + fn.id().namespace() + "/functions/" + fn.id().path() + ".mcfunction");
            Files.createDirectories(p.getParent());
            Files.writeString(p, fn.toFileContent(), StandardCharsets.UTF_8);
        }
    }

    private static void writeTagsDir(Path dir, Datapack dp) throws IOException {
        for (Tag tag : dp.tags()) {
            Path p = dir.resolve("data/" + tag.id().namespace() + "/tags/" + tag.type() + "/" + tag.id().path() + ".json");
            Files.createDirectories(p.getParent());
            Files.writeString(p, tagToJson(tag), StandardCharsets.UTF_8);
        }
    }

    private static void writeAdvancementsDir(Path dir, Datapack dp) throws IOException {
        for (Advancement adv : dp.advancements()) {
            Path p = dir.resolve("data/" + adv.id().namespace() + "/advancements/" + adv.id().path() + ".json");
            Files.createDirectories(p.getParent());
            Files.writeString(p, GSON.toJson(adv.raw()), StandardCharsets.UTF_8);
        }
    }

    private static void writeLootTablesDir(Path dir, Datapack dp) throws IOException {
        for (LootTable lt : dp.lootTables()) {
            Path p = dir.resolve("data/" + lt.id().namespace() + "/loot_tables/" + lt.id().path() + ".json");
            Files.createDirectories(p.getParent());
            Files.writeString(p, GSON.toJson(lt.raw()), StandardCharsets.UTF_8);
        }
    }

    /** Tag 序列化为 vanilla JSON。 */
    private static String tagToJson(Tag tag) {
        JsonObject o = new JsonObject();
        o.addProperty("replace", tag.replace());
        var arr = new com.google.gson.JsonArray();
        for (ResourceLocation v : tag.values()) {
            arr.add(v.toString());
        }
        o.add("values", arr);
        return GSON.toJson(o);
    }
}
