package dev.packweaver.bridge.pack;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;
import net.minecraft.client.MinecraftClient;
import net.minecraft.util.WorldSavePath;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

/**
 * 项目模型：一个项目 = 存档 datapacks/ 下的一份数据包 + 积木 AST 存储。
 * 事件积木保存于 packweaver.json（MC 会忽略该文件），保证双模式共享同一数据源。
 */
public class PackProject {
    public static final String META_FILE = "packweaver.json";
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

    public String name;
    public String namespace;
    /** 事件积木列表（每事件一棵树），双模式共享 */
    public List<BlockNode> events = new ArrayList<>();
    /** 手写文件（相对 data/ 路径 → 内容），IDE 模式直接编辑 */
    public Map<String, String> files = new TreeMap<>();

    private static Path datapacksDir() {
        var server = MinecraftClient.getInstance().getServer();
        if (server == null) {
            return null;
        }
        return server.getSavePath(WorldSavePath.DATAPACKS);
    }

    public static Path projectDir(String ns) {
        Path dir = datapacksDir();
        return dir == null ? null : dir.resolve("packweaver-" + ns);
    }

    public static PackProject load(String ns) throws IOException {
        Path dir = projectDir(ns);
        if (dir == null || !Files.exists(dir.resolve(META_FILE))) {
            throw new IOException("项目不存在: " + ns);
        }
        PackProject p = GSON.fromJson(Files.readString(dir.resolve(META_FILE)), PackProject.class);
        if (p.events == null) {
            p.events = new ArrayList<>();
        }
        if (p.files == null) {
            p.files = new TreeMap<>();
        }
        return p;
    }

    /** 列出存档中的全部 PackWeaver 项目命名空间。 */
    public static List<String> listProjects() {
        List<String> out = new ArrayList<>();
        Path dir = datapacksDir();
        if (dir == null || !Files.isDirectory(dir)) {
            return out;
        }
        try (var stream = Files.newDirectoryStream(dir, "packweaver-*")) {
            for (Path p : stream) {
                if (Files.exists(p.resolve(META_FILE))) {
                    out.add(p.getFileName().toString().substring("packweaver-".length()));
                }
            }
        } catch (IOException ignored) {
        }
        return out;
    }

    /** 保存：写出 pack.mcmeta、事件积木生成的函数、手写文件、AST 元数据。 */
    public void save() throws IOException {
        Path dir = projectDir(namespace);
        if (dir == null) {
            throw new IOException("未进入世界（找不到存档 datapacks 目录）");
        }
        // 积木 → 函数
        Map<String, String> generated = CodeGen.generate(namespace, events);
        // 手写文件覆盖同名生成文件（保证 IDE 模式修改不丢失）
        Map<String, String> all = new TreeMap<>(generated);
        all.putAll(files);

        writeIfChanged(dir.resolve("pack.mcmeta"), packMcmeta());
        for (Map.Entry<String, String> e : all.entrySet()) {
            writeIfChanged(dir.resolve("data").resolve(e.getKey()), e.getValue());
        }
        Files.writeString(dir.resolve(META_FILE), GSON.toJson(this));
    }

    private static String packMcmeta() {
        // 1.20.1 的 pack_format 为 15；后续版本可按需扩展
        int format = 15;
        return "{\"pack\": {\"pack_format\": " + format + ", \"description\": \"Generated by PackWeaver\"}}\n";
    }

    private static void writeIfChanged(Path target, String content) throws IOException {
        if (Files.exists(target) && Files.readString(target).equals(content)) {
            return;
        }
        Files.createDirectories(target.getParent());
        Files.writeString(target, content, StandardCharsets.UTF_8);
    }

    /** 读取项目内某个函数的当前代码（用于 IDE 模式打开）。 */
    public String readFunction(String fn) throws IOException {
        return readRaw(namespace + "/functions/" + fn + ".mcfunction");
    }

    /** 读取项目内任意数据文件（相对 data/ 的路径，如 ns/advancements/join.json）。 */
    public String readRaw(String relPath) throws IOException {
        Path dir = projectDir(namespace);
        Path f = dir.resolve("data").resolve(relPath);
        if (Files.exists(f)) {
            return Files.readString(f);
        }
        return files.getOrDefault(relPath, "");
    }

    /** IDE 模式保存函数：写文件并把该函数标记为手写（技术模式会显示为代码已自定义）。 */
    public void writeFunction(String fn, String content) throws IOException {
        writeRaw(namespace + "/functions/" + fn + ".mcfunction", content);
    }

    /** 保存任意数据文件（函数/JSON 等）。 */
    public void writeRaw(String relPath, String content) throws IOException {
        files.put(relPath, content);
        save();
    }

    /** 项目内全部文件（生成 + 手写），相对 data/ 的路径。 */
    public java.util.Set<String> allFiles() {
        java.util.Set<String> out = new java.util.TreeSet<>(CodeGen.generate(namespace, events).keySet());
        out.addAll(files.keySet());
        return out;
    }

    /** 导出 zip（pack.mcmeta 在 zip 根，data/ 在下）。返回文件路径。 */
    public Path exportZip() throws IOException {
        Path dir = projectDir(namespace);
        Path out = dir.getParent().resolve("PackWeaver-" + namespace + "-export.zip");
        Map<String, String> all = new TreeMap<>(CodeGen.generate(namespace, events));
        all.putAll(files);
        try (ZipOutputStream zip = new ZipOutputStream(Files.newOutputStream(out))) {
            zip.putNextEntry(new ZipEntry("pack.mcmeta"));
            zip.write(packMcmeta().getBytes(StandardCharsets.UTF_8));
            zip.closeEntry();
            for (Map.Entry<String, String> e : all.entrySet()) {
                zip.putNextEntry(new ZipEntry("data/" + e.getKey()));
                zip.write(e.getValue().getBytes(StandardCharsets.UTF_8));
                zip.closeEntry();
            }
        }
        return out;
    }

    public void delete() throws IOException {
        Path dir = projectDir(namespace);
        if (dir != null && Files.exists(dir)) {
            try (var walk = Files.walk(dir)) {
                walk.sorted(java.util.Comparator.reverseOrder()).forEach(p -> {
                    try {
                        Files.delete(p);
                    } catch (IOException ignored) {
                    }
                });
            }
        }
    }

    public static Gson gson() {
        return GSON;
    }

    public static TypeToken<PackProject> type() {
        return new TypeToken<>() {
        };
    }
}
